### ISSUE TITLE
LORA

### ISSUE THREAD

**Issue by ForserX** [ssube/onnx-web#213]
[# LoRA magic](https://github.com/ForserX/StableDiffusionUI/blob/3b0247e0cf264f0e4f1937a9b4daa8a88e90bace/data/repo/diffusion_scripts/sd_diffusers_cuda.py#L262)

There is a way to assemble LoRA + Diffusers on the fly. I will be glad if you figure out how to throw something like this in ONNX.

**Comment by ssube** [comment]
So I've been looking into this, and in theory, it is possible: https://github.com/ssube/onnx-web/blob/main/api/onnx_web/convert/diffusion/lora.py#L123

The difficulty seems to be in building a valid ONNX protobuf of the new model.

That code is not hooked up yet because I haven't been able to make it reliably emit valid models, but I'm not sure if that is a bug with the merge code or with the model checker. Adding too many initializers to the graph at once can cause a segfault in `onnx` or `protobuf` as well, but looping seemed to help with that (https://github.com/ssube/onnx-web/blob/main/api/onnx_web/convert/diffusion/lora.py#L85).

**Comment by ssube** [comment]
I've made some progress and done some research that may or may not be worth writing down, and see two issues so far:

- I think I have the UNet blended, at least it emits a valid model, but the `text_encoder/model.onnx` is primarily `.bias` nodes and missing a lot of `.weights` that I would expect. I'm not sure if that is a problem with the models, the conversion, or just the naming - there are a bunch of `onnx::MatMul` nodes that are linked to some of the nodes with "missing" weights, often as inputs. I'm wondering if the ONNX converter is losing the name on those nodes and I can follow the bias, or maybe this is something else entirely?
- the ONNX runtime's `InferenceSession` takes a model by filename/path or from a `bytes` object, but `model.SerializeToString()` has the 2GB protobuf limitation, and won't serialize the UNet to `bytes` in its whole form. Calling `convert_model_to_external_data`/`write_external_data_tensors` will write the extra data into an external protobuf _file_, but that doesn't have any way to write into memory (`bytes` or `BytesIO`). If you have a modern SSD or some Optane, that might not be a problem, but I need to raise issues/PRs with ONNX and ORT.

**Comment by ssube** [comment]
Looking at this further, with a little bit of progress:

It looks like ORT does offer a way to load external data from memory, so blending and even converting models without ever writing them to disk should be possible. For most of the large base models, saving them will still make sense, but that should save some SSD wear for LoRAs.

I was able to blend some models by looking up the MatMul nodes and write that out as a valid ONNX model, at least valid enough to load and run inference, but it comes out as random colored spots. Rather than guess at what the nodes mean, I'm writing a script to diff the ONNX models and working backwards from there.

<details>
<summary>diff script:</summary>

```python
from logging import getLogger, basicConfig, DEBUG
from numpy import maximum
from onnx import load_model, ModelProto
from onnx.numpy_helper import to_array
from sys import argv, stdout


basicConfig(stream=stdout, level=DEBUG)

logger = getLogger(__name__)

def diff_models(ref_model: ModelProto, cmp_model: ModelProto):
  if len(ref_model.graph.initializer) != len(cmp_model.graph.initializer):
    logger.warning("different number of initializers: %s vs %s", len(ref_model.graph.initializer), len(cmp_model.graph.initializer))
  else:
    for (ref_init, cmp_init) in zip(ref_model.graph.initializer, cmp_model.graph.initializer):
      if ref_init.name != cmp_init.name:
        logger.info("different node names: %s vs %s", ref_init.name, cmp_init.name)
      elif ref_init.data_location != cmp_init.data_location:
        logger.info("different data locations: %s vs %s", ref_init.data_location, cmp_init.data_location)
      elif ref_init.data_type != cmp_init.data_type:
        logger.info("different data types: %s vs %s", ref_init.data_type, cmp_init.data_type)
      elif len(ref_init.raw_data) != len(cmp_init.raw_data):
        logger.info("different raw data size: %s vs %s", len(ref_init.raw_data), len(cmp_init.raw_data))
      elif len(ref_init.raw_data) > 0 and len(cmp_init.raw_data) > 0:
        ref_data = to_array(ref_init)
        cmp_data = to_array(cmp_init)
        data_diff = ref_data - cmp_data
        if maximum(data_diff) > 0:
          logger.info("raw data differs: %s", data_diff)
      else:
        logger.info("initializers are identical in all checked fields: %s", ref_init.name)


if __name__ == "__main__":
  ref_path = argv[1]
  cmp_paths = argv[2:]

  logger.info("loading reference model from %s", ref_path)
  ref_model = load_model(ref_path)

  for cmp_path in cmp_paths:
    logger.info("loading comparison model from %s", cmp_path)
    cmp_model = load_model(cmp_path)
    diff_models(ref_model, cmp_model)
```
</details>

My initial comparison of two text_encoders is that all of the changes to initializers are in those `onnx::MatMul_2214` nodes, so my blending must be wrong somewhere.

```
INFO:__main__:raw data differs for onnx::MatMul_2214: [[-5.97857405e-04 -8.29659402e-05  2.55594961e-04 ... -3.97935510e-05
   1.16263516e-04 -2.64257425e-04]
 [-6.45183027e-05  1.43377110e-05 -1.45569444e-04 ... -2.29005702e-04
   3.29062605e-04 -6.15114346e-04]
 [-2.21131369e-04 -2.17929482e-05  2.85109505e-04 ... -1.59675255e-04
  -1.37356110e-04 -4.39988682e-04]
 ...
 [ 2.69189477e-05 -1.48676336e-05 -2.39353627e-04 ... -9.81168123e-05
   1.52554829e-04 -1.76237896e-04]
 [ 1.43175945e-04  6.34291209e-05  2.50307843e-04 ...  2.84195878e-04
   4.65737656e-04  3.63643281e-04]
 [ 1.87259167e-04  1.60088763e-04  1.67272985e-04 ... -1.12581765e-04
  -2.32110731e-04  3.32263298e-04]]
INFO:__main__:raw data differs for onnx::MatMul_2221: [[ 5.9778802e-05  1.2901332e-04 -2.7800910e-05 ... -5.8663264e-04
  -3.4572277e-04 -2.7506612e-05]
 [ 2.1521933e-04  6.2489137e-04  5.4099597e-05 ... -1.2307428e-05
  -8.6032785e-05  3.8439641e-05]
 [ 1.4275452e-04  5.2705873e-04  4.9114600e-04 ...  6.3313171e-05
   3.5880134e-05  3.1778496e-04]
 ...
 [ 1.3154559e-04 -3.6602188e-04  2.6111957e-06 ... -1.4451891e-04
  -5.4034032e-04 -1.6938546e-04]
 [ 5.1567703e-04  1.9872934e-04  6.5570464e-04 ...  7.1686227e-05
   2.2495119e-04 -2.4915300e-04]
 [-1.3470743e-04 -6.4091664e-04 -5.4577552e-04 ...  8.0384768e-04
```

**Comment by ForserX** [comment]
I want to say one thing. Even with Diffusers, LoRA models sometimes give out strange artifacts

**Comment by ssube** [comment]
I have something that seems to be working, with a few caveats:

- it only supports `nn.Linear` and `nn.Conv2d` 1x1 nodes (3x3 was added while I was working on this)
- changing the LoRA names and/or weights forces the model to be reloaded, but caching works otherwise
- you cannot add LoRAs to `extras.json` and convert/optimize them ahead of time
- optimizations may break this, I need to test that

What it does support so far:

- loading LoRAs from `.safetensors` in `onnx-web/models/lora/`
- blending LoRAs with the base ONNX model without ever writing it to disk
- blending with your selected diffusion model in the onnx-web UI
- parsing LoRA names from the prompt, using the `<lora:name:weight>` syntax

All of the good stuff is in https://github.com/ssube/onnx-web/blob/feat/213-lora/api/onnx_web/convert/diffusion/lora.py

Important parts, for my own reference and anyone else who finds them useful:

- the ONNX operator for `nn.Linear` is `MatMul` and `nn.Conv2d` is `Conv`
  - https://fdwr.github.io/LostOnnxDocs/OperatorFormulas.html is a really good reference for those
- exporting the Torch model to ONNX will remove the weights that need to be updated from the main nodes
- the nodes that actually need to be changed are inputs to those, the `MatMul` for `MatMul` and the `.weight` for `Conv`
  - https://github.com/ssube/onnx-web/blob/feat/213-lora/api/onnx_web/convert/diffusion/lora.py#L158
  - https://github.com/ssube/onnx-web/blob/feat/213-lora/api/onnx_web/convert/diffusion/lora.py#L184
- the normal https://github.com/kohya-ss/sd-scripts/blob/main/networks/merge_lora.py#L34 math applies to those
  - although I got a smaller diff between the models when transposing the MatMul weights: https://github.com/ssube/onnx-web/blob/feat/213-lora/api/onnx_web/convert/diffusion/lora.py#L196
- ONNX won't `.SerializeToString()` on models > 2GB unless you remove the `raw_data` first, but those do not need to be written to a file
- ONNX runtime loads the external data using its own type, `OrtValue`, and makes it part of the `SessionOptions`
- subtracting the values of the tensors between a model I had exported using the sd-scripts and my own output was really helpful

![image](https://user-images.githubusercontent.com/451959/225202148-511bbe2e-959c-456f-8f28-b5f16cf9cda5.png)
> `<lora:glass:1> <lora:arch:1> glasssculpture, glasssculpture of a conceptual architecture future office tower`
> Knollingcase, DEIS Multistep, 775942456, 8, 35

**Comment by ssube** [comment]
I have this working pretty well for LoRAs produced by the sd-scripts repo and most Textual Inversions, but it doesn't support the cloneofsimo LoRAs yet (#206). Let me know how this works for you, @ForserX, and if you or @Amblyopius have any info about getting the other networks working (hypernetworks, etc) I would be very interested.

I'm going to release what I have and the new ORT optimization stuff with 6/8GB support (#241) as v0.9.

**Comment by ForserX** [comment]
I hope to see it before the end of the month. While I'm dying at work...

**Comment by ForserX** [comment]
So, I lost a little "connection with the world"...
Do I need to use merge_to_sd_model or unpack first and then blend_loras?

**Comment by ForserX** [comment]
> getting the other networks working (hypernetworks, etc)

Regarding hypernetwork: I have only seen the implementation of auto111. But to me, a person far from Python, his code is like a personal hell, in which I understand only "None"

**Comment by ssube** [comment]
> Do I need to use merge_to_sd_model or unpack first and then blend_loras?

No need to merge. You can load the base model with `onnx.load_model` or pass the filename to `blend_loras`, and it will load the LoRA weights from the tensors directly: https://github.com/ssube/onnx-web/blob/main/api/onnx_web/convert/diffusion/lora.py#L67

```python
    base_model = base_name if isinstance(base_name, ModelProto) else load(base_name)
    lora_models = [load_tensor(name, map_location=device) for name, _weight in loras]
```

The nodes need to have the right names, and running some of the more aggressive ORT optimization scripts will break that.

The logic is pretty much normal, same as yours or sd-scripts, up until https://github.com/ssube/onnx-web/blob/main/api/onnx_web/convert/diffusion/lora.py#L170

**Comment by ForserX** [comment]
Good job! I tested it myself - it works great!
